using RestaurantManagement.Backend.Exceptions;
using RestaurantManagement.Backend.Services.Interfaces;
using RestaurantManagement.DataAccess.Models;
using RestaurantManagement.DataAccess.Repositories.Interfaces;
using RestaurantManagement.Dtos.Billing;
using RestaurantManagement.Dtos.Users;
using RestaurantManagement.Models.Common.Enums;

namespace RestaurantManagement.Backend.Services
{
    public class BillingService : IBillingService
    {
        private readonly IOrderRepository _orderRepo;
        private readonly IBillingRepository _billingRepo;
        private readonly ISettingsRepository _settingsRepo;
        private readonly ITableRepository _tableRepo;

        public BillingService(IOrderRepository orderRepo, IBillingRepository billingRepo, ISettingsRepository settingsRepo, ITableRepository tableRepo)
        {
            _orderRepo = orderRepo;
            _billingRepo = billingRepo;
            _settingsRepo = settingsRepo;
            _tableRepo = tableRepo;
        }

        public async Task<BillResponseDto> GenerateBillAsync(Guid waiterId, BillGenerateRequestDto dto)
        {
            var ordersId = dto.OrdersId;

            if (!ordersId.Any())
                throw new NotFoundException("Please give all the order ids");

            List<Order> orders = new List<Order>();
            foreach (var orderId in ordersId)
            {
                var order = await _orderRepo.GetOrderWithItemsAsync(orderId);
                if (order == null || order.Status != OrderStatus.Completed) throw new BadRequestException("All Orders are not completed yet");
                orders.Add(order);
            }

            var settings = await _settingsRepo.GetSettingsAsync() ?? throw new NotFoundException("Admin settings not configured.");
            if (orders.Any(o => o.TableId != orders[0].TableId))
                throw new BadRequestException("All orders must belong to same table.");
            var allItems = orders.SelectMany(o => o.Items).ToList();
            var subTotal = allItems.Sum(i => (i.Quantity*i.UnitPrice));
            var tableId = orders[0].TableId;
            var discountPercent = settings.DiscountPercent;
            var taxPercent = settings.TaxPercent;

            var discountAmount = (subTotal * discountPercent) / 100m;
            var taxable = subTotal - discountAmount;
            var taxAmount = (taxable * taxPercent) / 100m;
            var grandTotal = taxable + taxAmount;
            
            var bill = new Bill
            {
                Id = Guid.NewGuid(),
                CustomerId = dto.CustomerId,
                GeneratedByWaiterId = waiterId,
                SubTotal = subTotal,
                DiscountPercent = discountPercent,
                DiscountAmount = discountAmount,
                TaxPercent = taxPercent,
                TaxAmount = taxAmount,
                GrandTotal = grandTotal,
                IsPaymentDone = false,
                GeneratedAt = DateTime.UtcNow
            };

            await _billingRepo.AddAsync(bill);
            await _billingRepo.SaveChangesAsync();

            foreach (var order in orders)
            {
                order.IsBilled = true;
                order.BillingId = bill.Id;
                _orderRepo.Update(order);
            }

            await _orderRepo.SaveChangesAsync();
            var table = await _tableRepo.GetByIdAsync(tableId);
            table.IsOccupied = false;
            _tableRepo.Update(table);
            await _tableRepo.SaveChangesAsync();
            return new BillResponseDto
            {
                BillId = bill.Id,
                CustomerId = bill.CustomerId,
                SubTotal = bill.SubTotal,
                DiscountPercent = bill.DiscountPercent,
                DiscountAmount = bill.DiscountAmount,
                TaxPercent = bill.TaxPercent,
                TaxAmount = bill.TaxAmount,
                GrandTotal = bill.GrandTotal,
                IsPaymentDone = bill.IsPaymentDone,
                GeneratedAt = bill.GeneratedAt 
            };
        }

        public async Task<BillResponseDto> GetBillByIdAsync(Guid billId, Guid? waiterId, bool isAdmin)
        {
            var bill = await _billingRepo.GetBillDetailsAsync(billId)
                       ?? throw new NotFoundException("Bill not found.");

            if (isAdmin)
                return MapBillToDto(bill);

            if (!waiterId.HasValue || bill.GeneratedByWaiterId != waiterId.Value)
                throw new ForbiddenException("You can only view bills generated by you.");

            return MapBillToDto(bill);
        }

        public async Task<List<BillResponseDto>> GetBillsByCustomerIdAsync(Guid customerId, Guid? waiterId, bool isAdmin)
        {
            var bills = await _billingRepo.GetBillsByCustomerIdAsync(customerId);

            if (isAdmin || waiterId.HasValue)
                bills = bills.Where(b => b.GeneratedByWaiterId == waiterId.Value).ToList();
            else
                throw new ForbiddenException("No Access to the data");

            return bills.Select(MapBillToDto).ToList();
        }

        public async Task<List<BillResponseDto>> GetAllBillsAsync()
        {
            var bills = await _billingRepo.GetAllBillsAsync();
            return bills.Select(MapBillToDto).ToList();
        }

        public async Task UpdateBill(Guid billId, Guid waiterId, BillUpdateRequestDto dto)
        {
            var bill = await _billingRepo.GetByIdAsync(billId)
                       ?? throw new Exception("Bill not found.");

            if (bill.GeneratedByWaiterId != waiterId)
                throw new BadRequestException("You can update payment only for your own bill.");

            if (dto.IsPaymentDone.HasValue)
            {
                if(dto.IsPaymentDone.Value == true) 
                    throw new BadRequestException("You cannot update payment it is already done.");
                bill.IsPaymentDone = true;
            }
                
            _billingRepo.Update(bill);
            await _billingRepo.SaveChangesAsync();
        }

        private static BillResponseDto MapBillToDto(Bill bill)
        {
            return new BillResponseDto
            {
                BillId = bill.Id,
                CustomerId = bill.CustomerId,
                SubTotal = bill.SubTotal,
                DiscountPercent = bill.DiscountPercent,
                DiscountAmount = bill.DiscountAmount,
                TaxPercent = bill.TaxPercent,
                TaxAmount = bill.TaxAmount,
                GrandTotal = bill.GrandTotal,
                IsPaymentDone = bill.IsPaymentDone,
                GeneratedAt = bill.GeneratedAt
            };
        }
    }

}