using RestaurantManagement.Backend.Exceptions;
using RestaurantManagement.Backend.Services.Interfaces;
using RestaurantManagement.DataAccess.Models;
using RestaurantManagement.DataAccess.Repositories.Interfaces;
using RestaurantManagement.Dtos.Billing;
using RestaurantManagement.Dtos.Users;

namespace RestaurantManagement.Backend.Services
{
    public class BillingService : IBillingService
    {
        private readonly IOrderRepository _orderRepo;
        private readonly IBillingRepository _billingRepo;
        private readonly ISettingsRepository _settingsRepo;
        private readonly IGenericRepository<Table> _tableRepo;

        public BillingService(IOrderRepository orderRepo, IBillingRepository billingRepo, ISettingsRepository settingsRepo, IGenericRepository<Table> tableRepo)
        {
            _orderRepo = orderRepo;
            _billingRepo = billingRepo;
            _settingsRepo = settingsRepo;
            _tableRepo = tableRepo;
        }

        public async Task<BillResponseDto> GenerateBillAsync(Guid customerId, Guid waiterId)
        {
            var orders = await _orderRepo.GetCompletedUnbilledOrdersByCustomerAsync(customerId);

            if (orders.Count == 0)
                throw new NotFoundException("No completed unbilled orders found for this customer.");

            var settings = await _settingsRepo.GetSettingsAsync()
                           ?? throw new NotFoundException("Admin settings not configured.");

            var orderIds = orders.Select(x => x.Id).ToList();
            var allItems = orders.SelectMany(o => o.Items).ToList();
            var subTotal = allItems.Sum(i => (i.Quantity*i.UnitPrice));
            var tableId = orders[0].TableId;
            var discountPercent = settings.DiscountPercent;
            var taxPercent = settings.TaxPercent;

            var discountAmount = (subTotal * discountPercent) / 100m;
            var taxable = subTotal - discountAmount;
            var taxAmount = (taxable * taxPercent) / 100m;
            var grandTotal = taxable + taxAmount;

            var bill = new Bill
            {
                Id = Guid.NewGuid(),
                CustomerId = customerId,
                GeneratedByWaiterId = waiterId,
                SubTotal = subTotal,
                DiscountPercent = discountPercent,
                DiscountAmount = discountAmount,
                TaxPercent = taxPercent,
                TaxAmount = taxAmount,
                GrandTotal = grandTotal,
                IsPaymentDone = false,
                GeneratedAt = DateTime.UtcNow
            };

            await _billingRepo.AddAsync(bill);
            await _billingRepo.SaveChangesAsync();

            foreach (var order in orders)
            {
                order.IsBilled = true;
                order.BillingId = bill.Id;
                _orderRepo.Update(order);
            }

            await _orderRepo.SaveChangesAsync();
            var table = await _tableRepo.GetByIdAsync(tableId);
            table.IsOccupied = false;
            _tableRepo.Update(table);
            return new BillResponseDto
            {
                BillId = bill.Id,
                CustomerId = bill.CustomerId,
                SubTotal = bill.SubTotal,
                DiscountPercent = bill.DiscountPercent,
                DiscountAmount = bill.DiscountAmount,
                TaxPercent = bill.TaxPercent,
                TaxAmount = bill.TaxAmount,
                GrandTotal = bill.GrandTotal,
                IsPaymentDone = bill.IsPaymentDone,
                GeneratedAt = bill.GeneratedAt 
            };
        }

        public async Task<BillResponseDto> GetBillByIdAsync(Guid billId, Guid? waiterId, bool isAdmin)
        {
            var bill = await _billingRepo.GetBillDetailsAsync(billId)
                       ?? throw new NotFoundException("Bill not found.");

            if (!isAdmin || (waiterId.HasValue && bill.GeneratedByWaiterId != waiterId.Value))
                throw new BadRequestException("You can only view bills generated by you.");

            return MapBillToDto(bill);
        }

        public async Task<List<BillResponseDto>> GetBillsByCustomerIdAsync(Guid customerId, Guid? waiterId, bool isAdmin)
        {
            var bills = await _billingRepo.GetBillsByCustomerIdAsync(customerId);

            if (isAdmin || waiterId.HasValue)
                bills = bills.Where(b => b.GeneratedByWaiterId == waiterId.Value).ToList();

            return bills.Select(MapBillToDto).ToList();
        }

        public async Task<List<BillResponseDto>> GetAllBillsAsync()
        {
            var bills = await _billingRepo.GetAllBillsAsync();
            return bills.Select(MapBillToDto).ToList();
        }

        public async Task UpdateBill(Guid billId, Guid waiterId, BillUpdateRequestDto dto)
        {
            var bill = await _billingRepo.GetByIdAsync(billId)
                       ?? throw new Exception("Bill not found.");

            if (bill.GeneratedByWaiterId != waiterId)
                throw new BadRequestException("You can update payment only for your own bill.");

            if (dto.IsPaymentDone.HasValue)
            {
                if(dto.IsPaymentDone.Value == true) 
                    throw new BadRequestException("You cannot update payment it is already done.");
                bill.IsPaymentDone = true;
            }
                
            _billingRepo.Update(bill);
            await _billingRepo.SaveChangesAsync();
        }

        private static BillResponseDto MapBillToDto(Bill bill)
        {
            return new BillResponseDto
            {
                BillId = bill.Id,
                CustomerId = bill.CustomerId,
                SubTotal = bill.SubTotal,
                DiscountPercent = bill.DiscountPercent,
                DiscountAmount = bill.DiscountAmount,
                TaxPercent = bill.TaxPercent,
                TaxAmount = bill.TaxAmount,
                GrandTotal = bill.GrandTotal,
                IsPaymentDone = bill.IsPaymentDone,
                GeneratedAt = bill.GeneratedAt
            };
        }
    }

}